### ISSUE TITLE
Prepare Plugin for WP.org Repo - Minimum fixes

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods-caldera-forms#14]
The items outstanding mostly appear to be specific to images and upload fields:

- [ ] Featured Image does not map to WP Object (missing in list, but in Custom Fields add-on) #8 
- [ ] Uploaded Files & Images get mapped to the Media Library but not to the File/Image/Media field #7 
- [ ] Autocomplete Relationship fields from Pods can't seem to locate the Autocomplete fields in the form. #11 

I believe these are the most pertinent to get the plugin ready for the WordPress.org repo.

**Comment by jimtrue** [comment]
@Shelob9 Per your request, thinned down the task list for getting this plugin ready for the WordPress.org repo and validated the 3 most specific bugs.

**Comment by Shelob9** [comment]
BTW I am working on major refactor for Caldera Forms editor UI. One of the goals, besides performance is to make tricky UIs like this one requires not a pain in the ass. So CF Pods is blocked by https://github.com/CalderaWP/Caldera-Forms/issues/1355 which hopefully will be done soon. Once Caldera Forms 1.5.1 is done, this can be completed.

**Comment by jimtrue** [comment]
"Language, Cap'n"

**Comment by Shelob9** [comment]
Language adjusted.

**Comment by jimtrue** [comment]
@Shelob9 Any update on this one? I know you've been pointing folks to your Caldera Custom Fields Add-on (https://wordpress.org/plugins/caldera-form-metabox/) but that wouldn't work with the Relationship Fields from Pods and File/Media fields only work as 'attachments' not as File Fields. Is there any chance you can revisit this update or make a better suggestion?

**Comment by dmsdesignz** [comment]
any updates on this?

**Comment by bkonia** [comment]
Any updates?

**Comment by ericmil87** [comment]
Any solutions? All what @jimtrue said is true and need to be fixed 👍
